format:
  html: 
    theme: zephyr

project:
  type: book

book:
  title: "Numerical Methods in Applied Mathematics, with Python"
  author: "Mario Ba√±uelos, Ph.D."
  sidebar:
    logo: "nmam.png"
  favicon: "nmam.png"
  chapters:
    - index.qmd
    - preface.qmd
    - part: module_one.ipynb
      chapters:
        - week1.ipynb
        - week2.ipynb
    - part: module_two.ipynb
      chapters:
        - week3.ipynb
        - week4.ipynb
        - week5.ipynb
    - part: module_three.ipynb
      chapters:
        - week6.ipynb
        - week7.ipynb
        - week8.ipynb
    - part: module_four.ipynb
      chapters:
        - week9.ipynb
        - week10.ipynb
        - week11.ipynb
        - week12.ipynb
        - week13_advection_fd.ipynb
    - part: module_five.ipynb
      chapters:
        - week14_advection_fv.ipynb
execute:
  echo: true

launch:
  colab: true
